#!/bin/sh

set -e

[ -f /etc/default/vcentercollector ] && . /etc/default/vcentercollector

startvcentercollector() {
  if [ -x /bin/systemctl ]; then
    /bin/systemctl daemon-reload
    /bin/systemctl restart vcentercollector
	elif [ -x "/etc/init.d/vcentercollector" ]; then
		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
			invoke-rc.d vcentercollector restart || true
		else
			/etc/init.d/vcentercollector restart || true
		fi
	fi
}

case "$1" in
	configure)
	[ -z "$RESIST_USER" ] && RESIST_USER="resist"
	[ -z "$RESIST_GROUP" ] && RESIST_GROUP="resist"
	if ! getent group "$RESIST_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$RESIST_GROUP" --quiet
	fi
	if ! id $RESIST_USER > /dev/null 2>&1 ; then
	    adduser --system --home /usr/share/vcentercollector --no-create-home \
		--ingroup "$RESIST_GROUP" --disabled-password --shell /bin/false \
		"$RESIST_USER"
	fi

  if [ -x /opt/vcentercollector/ ]; then
    echo "### Upgrading Notice ### "
    echo "-- New vcentercollector install home is /usr/share/vcentercollector"
    #echo "-- Please move sqlite3 database to /var/lib/vcentercollector/"
    echo "-- Notice: service name && binary changed to vcentercollector"
  fi

	# Set user permissions on /var/log/vcentercollector, /var/lib/vcentercollector
	mkdir -p /var/log/vcentercollector /var/lib/vcentercollector
	chown -R $RESIST_USER:$RESIST_GROUP /var/log/vcentercollector /var/lib/vcentercollector
	chmod 755 /var/log/vcentercollector /var/lib/vcentercollector

	# configuration files should not be modifiable by vcentercollector user, as this can be a security issue
	chown -Rh root:$RESIST_GROUP /etc/vcentercollector/*
	chmod 755 /etc/vcentercollector
	find /etc/vcentercollector -type f -exec chmod 640 {} ';'
	find /etc/vcentercollector -type d -exec chmod 755 {} ';'

	# if $2 is set, this is an upgrade
	if ( [ -n $2 ] && [ "$RESTART_ON_UPGRADE" = "true" ] ) ; then
		startvcentercollector
	# this is a fresh installation
	elif [ -z $2 ] ; then
        if [ -x /bin/systemctl ] ; then
            echo "### NOT starting on installation, please execute the following statements to configure vcentercollector to start automatically using systemd"
            echo " sudo /bin/systemctl daemon-reload"
            echo " sudo /bin/systemctl enable vcentercollector"
            echo "### You can start vcentercollector by executing"
            echo " sudo /bin/systemctl start vcentercollector"

        elif [ -x /usr/sbin/update-rc.d ] ; then
            echo "### NOT starting vcentercollector by default on bootup, please execute"
            echo " sudo update-rc.d vcentercollector defaults 95 10"
            echo "### In order to start vcentercollector, execute"
            echo " sudo service vcentercollector start"
        fi
	fi
	;;
esac
